import { test, expect } from '@playwright/test'
import { paymentReviewFixture } from '../paymentReviewFixture.js'
import { unwrap } from '../../src/client/booking/bookingApi.js'

let f
const created = []
test.beforeEach(async () => { f = await paymentReviewFixture(); created.length = 0 })
test.afterEach(async () => {
  for (const id of created) await f.admin.from('clients').delete().eq('id', id)
  await f.admin.from('clients').delete().like('email', 'e2e-clients-%')
  await f?.cleanup()
})

async function signIn(page, path = '/admin/clients') {
  await page.goto(path)
  await page.getByLabel('Email', { exact: true }).fill(f.email)
  await page.getByLabel('Password', { exact: true }).fill(f.password)
  await page.getByRole('button', { name: 'Sign in', exact: true }).click()
}
async function client(overrides = {}) {
  const row = await unwrap(f.admin.from('clients').insert({ first_name: 'Zelda', last_name: 'Searchable', email: `e2e-clients-${crypto.randomUUID()}@example.test`, phone: '07700 900777', ...overrides }).select().single())
  created.push(row.id)
  return row
}
const profile = (page, name) => page.getByRole('heading', { name, level: 1 })

test('a client can be found by name, phone or email and opened', async ({ page }) => {
  await f.authorize()
  const row = await client()
  await signIn(page)
  await expect(page.getByRole('heading', { name: 'Clients', level: 1 })).toBeVisible()
  await page.getByLabel('Search by name, phone or email').fill('zelda search')
  await page.getByRole('button', { name: /Zelda Searchable/ }).click()
  await expect(profile(page, 'Zelda Searchable')).toBeVisible()
  await expect(page).toHaveURL(new RegExp(`/admin/clients/${row.id}$`))
  await expect(page.getByText('None booked')).toBeVisible()
  await page.getByRole('button', { name: '← Clients' }).click()
  await page.getByLabel('Search by name, phone or email').fill('900777')
  await expect(page.getByRole('button', { name: /Zelda Searchable/ })).toBeVisible()
  await page.getByLabel('Search by name, phone or email').fill('nobody-called-this')
  await expect(page.getByText('No one matches that search.')).toBeVisible()
})

test('details can be edited, and another client\'s email is refused kindly', async ({ page }) => {
  await f.authorize()
  const row = await client()
  const other = await client({ first_name: 'Orla', last_name: 'Other', phone: '07700 900778' })
  await signIn(page, `/admin/clients/${row.id}`)
  await expect(profile(page, 'Zelda Searchable')).toBeVisible()
  const links = page.getByRole('navigation', { name: 'Quick contact' })
  await expect(links.getByRole('link', { name: 'WhatsApp' })).toHaveAttribute('href', 'https://wa.me/447700900777')
  await page.getByRole('button', { name: 'Edit details' }).click()
  const form = page.getByRole('region', { name: 'Edit details' })
  await form.getByLabel('Email').fill(other.email)
  await form.getByRole('button', { name: 'Save details' }).click()
  await expect(form.getByRole('alert')).toHaveText('Another client already uses this email or phone.')
  await form.getByLabel('Email').fill(`e2e-clients-${crypto.randomUUID()}@example.test`)
  await form.getByLabel('First name').fill('Zelda Jane')
  await form.getByRole('button', { name: 'Save details' }).click()
  await expect(profile(page, 'Zelda Jane Searchable')).toBeVisible()
  expect((await f.admin.from('clients').select('first_name').eq('id', row.id).single()).data.first_name).toBe('Zelda Jane')
  await page.getByRole('button', { name: 'Edit details' }).click()
  await page.getByLabel('Phone').fill('')
  await page.getByLabel('Email').fill('')
  await expect(page.getByText('Enter a phone number or an email address.')).toBeVisible()
  await expect(page.getByRole('button', { name: 'Save details' })).toBeDisabled()
})

test('addresses can be added, changed, made default and removed with a confirmation', async ({ page }) => {
  await f.authorize()
  const row = await client()
  await signIn(page, `/admin/clients/${row.id}`)
  await expect(page.getByText('No saved addresses yet.')).toBeVisible()
  await page.getByRole('button', { name: '+ Add address' }).click()
  await page.getByLabel('Street and number').fill('12 Garden Road')
  await page.getByLabel('Postcode').fill('sw1a 2aa')
  await page.getByRole('button', { name: 'Add address' }).click()
  await expect(page.getByText('12 Garden Road, London, sw1a 2aa')).toBeVisible()
  await page.getByRole('button', { name: '+ Add address' }).click()
  await page.getByLabel('Street and number').fill('7 Office Lane')
  await page.getByLabel('Postcode').fill('EC1A 1BB')
  await page.getByRole('button', { name: 'Add address' }).click()
  const second = page.locator('.admin-address-list li').filter({ hasText: '7 Office Lane' })
  await second.getByRole('button', { name: 'Make default' }).click()
  await expect(second).toContainText('Default')
  const defaults = (await f.admin.from('client_addresses').select('address_line_1,is_default').eq('client_id', row.id)).data
  expect(defaults.filter(item => item.is_default).map(item => item.address_line_1)).toEqual(['7 Office Lane'])
  await second.getByRole('button', { name: 'Change' }).click()
  await page.getByLabel('Entry instructions (optional)').fill('Ring the top bell')
  await page.getByRole('button', { name: 'Save address' }).click()
  await expect(second).toContainText('Ring the top bell')
  const first = page.locator('.admin-address-list li').filter({ hasText: '12 Garden Road' })
  await first.getByRole('button', { name: 'Remove' }).click()
  await expect(first).toContainText('Past bookings keep their own copy of it.')
  await first.getByRole('button', { name: 'Yes, remove' }).click()
  await expect(page.getByText('12 Garden Road')).toHaveCount(0)
})

test('notes can be added and deleted, and online booking can be switched off and on', async ({ page }) => {
  await f.authorize()
  const row = await client()
  await signIn(page, `/admin/clients/${row.id}`)
  await page.getByLabel('Add a note').fill('Prefers firm pressure on the shoulders')
  await page.getByRole('button', { name: 'Save note' }).click()
  await expect(page.locator('.admin-note-list')).toContainText('Prefers firm pressure on the shoulders')
  expect((await f.admin.from('client_notes').select('author_user_id').eq('client_id', row.id).single()).data.author_user_id).toBe(f.user.id)
  await page.getByRole('button', { name: /Delete the note from/ }).click()
  await expect(page.getByText('No notes yet.')).toBeVisible()
  await page.getByRole('button', { name: 'Switch off online booking' }).click()
  await expect(page.getByText('Online booking is switched off for this client.')).toBeVisible()
  expect((await f.admin.from('clients').select('online_booking_enabled').eq('id', row.id).single()).data.online_booking_enabled).toBe(false)
  await page.getByRole('button', { name: 'Switch on online booking' }).click()
  await expect(page.getByText('This client can book online.')).toBeVisible()
})

test('a new client can be added with an address, and opens straight away', async ({ page }) => {
  await f.authorize()
  await signIn(page)
  await page.getByRole('button', { name: '+ Add client' }).click()
  const email = `e2e-clients-${crypto.randomUUID()}@example.test`
  const form = page.getByRole('region', { name: 'Add a client' })
  await form.getByLabel('First name').fill('Wanda')
  await form.getByLabel('Last name').fill('Newcomer')
  await form.getByLabel('Email').fill(email)
  await expect(form.getByRole('button', { name: 'Add client' })).toBeDisabled()
  await form.getByLabel('Street and number').fill('3 Fresh Close')
  await form.getByLabel('Postcode').fill('W1A 1AA')
  await form.getByRole('button', { name: 'Add client' }).click()
  await expect(profile(page, 'Wanda Newcomer')).toBeVisible()
  await expect(page.getByText('3 Fresh Close, London, W1A 1AA')).toBeVisible()
  await page.getByRole('button', { name: '← Clients' }).click()
  await page.getByRole('button', { name: '+ Add client' }).click()
  const again = page.getByRole('region', { name: 'Add a client' })
  await again.getByLabel('First name').fill('Wanda')
  await again.getByLabel('Email').fill(email)
  await again.getByLabel('Street and number').fill('3 Fresh Close')
  await again.getByLabel('Postcode').fill('W1A 1AA')
  await again.getByRole('button', { name: 'Add client' }).click()
  await expect(again.getByRole('alert')).toContainText('An existing client uses this email or phone.')
})

test('booking history opens the booking and returns to the client, and a new booking starts with the client chosen', async ({ page }) => {
  await f.authorize()
  const owner = (await f.admin.from('bookings').select('client_id,booking_reference').eq('id', f.bookings[2].id).single()).data
  await signIn(page, `/admin/clients/${owner.client_id}`)
  await expect(page.getByRole('heading', { name: 'Bookings' })).toBeVisible()
  const history = page.locator('.admin-client-bookings li')
  await expect(history.first()).toBeVisible()
  await history.first().getByRole('button').click()
  await expect(page.locator('dialog.admin-details')).toBeVisible()
  await page.getByRole('button', { name: 'Close details' }).click()
  await expect(page).toHaveURL(new RegExp(`/admin/clients/${owner.client_id}$`))
  await page.getByRole('button', { name: '+ New booking' }).click()
  await expect(page.getByRole('heading', { name: 'New booking', exact: true })).toBeVisible()
  await expect(page.getByRole('button', { pressed: true }).first()).toContainText('Alexandra')
})
