import { test, expect } from '@playwright/test'
import { adminFixture } from '../adminFixture.js'
import { bookingState, dayTimeline, sessionSummary } from '../../src/admin/calendarPresentation.js'
let f
test.beforeEach(async () => { f = await adminFixture() })
test.afterEach(async () => { await f?.cleanup() })
async function login(page) {
  await page.goto('/admin')
  await expect(page.getByRole('heading', { name: 'Admin sign in' })).toBeVisible()
  await expect(page.getByText('Continue as guest')).toHaveCount(0)
  await page.getByLabel('Email', { exact: true }).fill(f.email)
  await page.getByLabel('Password', { exact: true }).fill(f.password)
  await page.getByRole('button', { name: 'Sign in', exact: true }).click()
}
test('normal client is denied Admin access', async ({ page }) => {
  await login(page); await expect(page.getByRole('alert')).toContainText('does not have Admin access')
  await expect(page.getByLabel('Day appointments')).toHaveCount(0)
})
for (const width of [320, 360, 390, 412]) test(`real calendar and exact persisted details fit ${width}px`, async ({ page }) => {
  const ranges = []
  page.on('request', request => { const url = new URL(request.url()); if (url.pathname === '/rest/v1/bookings') ranges.push(url.searchParams.getAll('date')) })
  await f.authorize(); await page.setViewportSize({ width, height: 844 }); await login(page)
  await page.getByLabel('Calendar date', { exact: true }).fill(f.date)
  await expect(page.locator('.admin-card')).toHaveCount(2)
  await expect(page.getByRole('list', { name: 'Day timeline' })).toBeVisible()
  await expect(page.locator('.admin-card').first().locator('.admin-card-heading')).toContainText('£85.00')
  await expect(page.locator('.admin-card').first().locator('.admin-card-treatment')).toContainText('60 min')
  await expect(page.locator('.admin-card').first().locator('.admin-card-postcode')).toHaveText('SW1A 1AA')
  await expect(page.locator('.admin-card').first().locator('.admin-status')).toHaveText('Confirmed · Cash approved')
  expect((await page.locator('.admin-header').boundingBox()).height).toBeLessThanOrEqual(110)
  await expect(page.getByText('Day context', { exact: true })).toHaveCount(0)
  await expect(page.getByText('Unoccupied intervals', { exact: true })).toHaveCount(0)
  const starts = await page.locator('.admin-timeline-row').evaluateAll(rows => rows.map(row => Number(row.dataset.start)))
  expect(starts).toEqual([...starts].sort((a, b) => a - b))
  await page.screenshot({ path: `test-results/admin-agenda-${width}.png`, fullPage: true })
  expect(ranges.some(values => values.includes('gte.' + f.date) && values.some(value => value.startsWith('lt.')))).toBe(true)
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.locator('.admin-card').first().click()
  await expect(page.getByRole('dialog')).toContainText(f.bookings[0].booking_reference)
  await expect(page.getByRole('dialog')).toContainText('booking@example.test')
  await expect(page.getByRole('dialog')).toContainText('Exact persisted note')
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  expect(await page.getByRole('dialog').evaluate(el => el.scrollWidth <= el.clientWidth)).toBe(true)
  const dialogBox = await page.getByRole('dialog').boundingBox()
  expect(dialogBox).toMatchObject({ x: 0, y: 0, width, height: 844 })
  await expect(page.getByRole('dialog')).toContainText(f.bookings[0].address_line_1_snapshot)
  await expect(page.getByRole('dialog')).toContainText(`Session ${f.bookings[0].booking_reference}`)
  await page.getByRole('dialog').evaluate(dialog => { dialog.scrollTop = 400 })
  await expect(page.getByRole('button', { name: 'Close details' })).toBeInViewport()
  expect(await page.getByRole('dialog').evaluate(el => el.scrollWidth <= el.clientWidth)).toBe(true)
  await page.getByRole('dialog').evaluate(dialog => { dialog.scrollTop = 0 })
  await page.screenshot({ path: `test-results/admin-details-${width}.png`, fullPage: true })
  await page.getByRole('button', { name: 'Close details' }).click()
  await page.locator('.admin-card.cancelled').click()
  await expect(page.getByRole('dialog')).toContainText(f.bookings[1].booking_reference)
  await expect(page.getByRole('dialog')).toContainText('Rejected')
  await page.getByRole('button', { name: 'Close details' }).click()
  await page.getByRole('button', { name: 'Next day' }).click()
  await expect(page.locator('.admin-card')).toHaveCount(1)
  await page.locator('.admin-card').click()
  await expect(page.getByRole('dialog')).toContainText(f.bookings[2].booking_reference)
})
test('calendar error is visible and retry recovers', async ({ page }) => {
  await f.authorize(); await login(page)
  await page.route('**/rest/v1/bookings?**', route => route.fulfill({ status: 403, contentType: 'application/json', body: JSON.stringify({ message: 'Calendar read denied', code: '42501' }) }))
  await page.getByLabel('Calendar date', { exact: true }).fill(f.date)
  await expect(page.getByRole('alert')).toContainText('Could not load calendar')
  await expect(page.getByText('No appointments for this day.')).toHaveCount(0)
  await page.unroute('**/rest/v1/bookings?**')
  await page.getByRole('button', { name: 'Retry calendar' }).click()
  await expect(page.locator('.admin-card')).toHaveCount(2)
})

test('authentication errors are visible and signed-out data is absent', async ({ page }) => {
  await page.goto('/admin')
  await page.getByLabel('Email', { exact: true }).fill(f.email)
  await page.getByLabel('Password', { exact: true }).fill('incorrect-password')
  await page.getByRole('button', { name: 'Sign in', exact: true }).click()
  await expect(page.getByRole('alert')).toContainText('Invalid login credentials')
  await expect(page.locator('.admin-card')).toHaveCount(0)
})

test('presentation preserves scheduling context and truthful payment labels', () => {
  const now = Date.now()
  const booking = { id: 'booking', booking_status: 'confirmed', start_minutes: 660, treatment_duration_minutes: 60, travel_buffer_minutes: 15, booking_payments: { method: 'cash', status: 'approved' }, booking_sessions: [{ service_name_snapshot: 'Deep Tissue', duration_minutes: 60 }] }
  const cancelled = { ...booking, id: 'cancelled', start_minutes: 840, booking_status: 'cancelled' }
  const data = { bookings: [booking, cancelled], blocks: [{ id: 'block', start_minutes: 750, end_minutes: 780, title: 'Lunch' }], holds: [{ id: 'hold', start_minutes: 780, treatment_duration_minutes: 30, travel_buffer_minutes: 5, expires_at: new Date(now + 60000).toISOString() }, { id: 'expired', expires_at: new Date(now - 1).toISOString() }], overrides: [{ date: f.date, available: true, start_minutes: 600, end_minutes: 1080 }], hours: [] }
  const timeline = dayTimeline(data, f.date, now)
  expect(timeline.rows.map(row => row.start)).toEqual(timeline.rows.map(row => row.start).sort((a, b) => a - b))
  expect(timeline.rows.filter(row => row.kind === 'hold').map(row => row.id)).toEqual(['hold'])
  expect(timeline.rows.filter(row => row.kind === 'buffer').map(row => [row.start, row.end])).toEqual([[645, 660], [720, 735], [775, 780], [810, 815]])
  expect(timeline.rows.filter(row => row.kind === 'free').map(row => [row.start, row.end])).toEqual([[600, 645], [735, 750], [815, 840], [840, 900], [900, 1080]])
  expect(bookingState(booking, now).text).toBe('Confirmed · Cash approved')
  expect(bookingState({ ...booking, booking_payments: { status: 'paid' } }, now).text).toBe('Confirmed · Paid')
  expect(bookingState({ ...booking, booking_status: 'awaiting_payment_verification' }, now).tone).toBe('pending')
  expect(bookingState({ ...booking, booking_status: 'awaiting_cash_approval' }, now).text).toBe('Awaiting cash approval')
  expect(sessionSummary(booking)).toBe('Deep Tissue · 60 min')
  expect(sessionSummary({ ...booking, treatment_duration_minutes: 180, booking_sessions: [{}, {}, {}] })).toBe('3 sessions · 180 min')
  expect(dayTimeline({ ...data, overrides: [{ date: f.date, available: false }] }, f.date, now).rows.some(row => ['free', 'boundary'].includes(row.kind))).toBe(false)
})

test('agenda integrates holds and blocks; compact controls scroll and account signs out', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 480 })
  await f.authorize()
  // Presentation fixtures supplement real authenticated reads without DB writes.
  await page.route('**/rest/v1/calendar_blocks?**', route => route.fulfill({ json: [{ id: 'display-block', start_minutes: 690, end_minutes: 720, title: 'Lunch break' }] }))
  await page.route('**/rest/v1/booking_holds?**', route => route.fulfill({ json: [{ id: 'display-hold', start_minutes: 750, treatment_duration_minutes: 30, travel_buffer_minutes: 15, expires_at: new Date(Date.now() + 120000).toISOString() }] }))
  await page.route('**/rest/v1/bookings?**', async route => {
    const response = await route.fetch()
    const rows = await response.json()
    await route.fulfill({ response, json: rows.map(row => ({ ...row, clients: { ...row.clients, first_name: 'Alexandra', last_name: 'Calendar' } })) })
  })
  await login(page)
  await page.getByLabel('Calendar date', { exact: true }).fill(f.date)
  await expect(page.locator('.admin-card')).toHaveCount(2)
  await expect(page.getByText('Temporary hold', { exact: true })).toBeVisible()
  await expect(page.getByText('Lunch break', { exact: true })).toBeVisible()
  await expect(page.getByText('Travel / buffer', { exact: true }).first()).toBeVisible()
  await expect(page.getByText('Working day starts', { exact: true })).toBeVisible()
  await expect(page.getByText('Working day ends', { exact: true })).toBeVisible()
  expect((await page.locator('.admin-card').first().boundingBox()).height).toBeLessThan(160)
  await page.screenshot({ path: 'test-results/admin-agenda-context.png', fullPage: true })
  await page.evaluate(() => { document.activeElement.blur(); window.scrollTo(0, 200) })
  await expect(page.locator('.admin-header')).toHaveClass(/is-hidden/)
  await page.evaluate(() => window.scrollBy(0, -20))
  await expect(page.locator('.admin-header')).not.toHaveClass(/is-hidden/)
  await page.getByRole('button', { name: 'Account menu' }).click()
  await page.getByRole('button', { name: 'Sign out', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Admin sign in' })).toBeVisible()
})

test('desktop uses the same details component as a right-side panel and Escape restores focus', async ({ page }) => {
  await f.authorize(); await page.setViewportSize({ width: 1280, height: 900 }); await login(page)
  await page.getByLabel('Calendar date', { exact: true }).fill(f.date)
  await page.locator('.admin-card').first().click()
  const dialog = page.getByRole('dialog')
  const box = await dialog.boundingBox()
  expect(box.width).toBeGreaterThanOrEqual(520)
  expect(box.width).toBeLessThanOrEqual(600)
  expect(box.x + box.width).toBe(1280)
  expect(await dialog.evaluate(el => el.scrollWidth <= el.clientWidth)).toBe(true)
  await page.screenshot({ path: 'test-results/admin-details-desktop.png', fullPage: true })
  await page.keyboard.press('Escape')
  await expect(dialog).toHaveCount(0)
  await expect(page.locator('.admin-card').first()).toBeFocused()
})
