import { test, expect } from '@playwright/test'
import { paymentReviewFixture } from '../paymentReviewFixture.js'
let f
test.beforeEach(async () => { f = await paymentReviewFixture() })
test.afterEach(async () => { await f?.cleanup() })
async function login(page, path = '/admin/review') {
  await page.goto(path)
  await page.getByLabel('Email', { exact: true }).fill(f.email)
  await page.getByLabel('Password', { exact: true }).fill(f.password)
  await page.getByRole('button', { name: 'Sign in', exact: true }).click()
}
const item = (page, index) => page.locator('.admin-review-item').filter({ hasText: f.bookings[index].booking_reference })
async function confirm(page, button) {
  await button.click()
  const confirmation = page.locator('dialog.admin-confirm')
  await expect(confirmation).toBeVisible()
  await confirmation.getByRole('button', { name: /^Confirm / }).click()
}
for (const width of [320, 360, 390, 412]) test(`Review, confirmation and exact booking deep link fit ${width}px`, async ({ page }) => {
  await f.authorize(); await page.setViewportSize({ width, height: 844 })
  const requests = []
  page.on('request', request => { if (request.url().includes('/rest/v1/')) requests.push(request.url()) })
  await login(page)
  await expect(page).toHaveURL(/\/admin\/review$/)
  await expect(page.locator('.admin-review-item')).toHaveCount(2)
  expect(requests.some(url => url.includes('/rest/v1/bookings?'))).toBe(false)
  expect(requests.filter(url => url.includes('/admin_payment_review_queue'))).toHaveLength(1)
  await expect(page.getByRole('navigation', { name: 'Admin navigation' })).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await item(page, 1).getByRole('button', { name: 'Remove booking', exact: true }).click()
  const confirmation = page.getByRole('dialog')
  await expect(confirmation).toContainText('recorded as cancelled')
  expect(await confirmation.evaluate(el => el.scrollWidth <= el.clientWidth)).toBe(true)
  await page.screenshot({ path: `test-results/admin-review-confirm-${width}.png` })
  await confirmation.getByRole('button', { name: 'Go back' }).click()
  await page.screenshot({ path: `test-results/admin-review-${width}.png`, fullPage: true })
  await item(page, 0).getByRole('link', { name: 'View booking' }).click()
  await expect(page).toHaveURL(new RegExp(`/admin/bookings/${f.bookings[0].id}$`))
  const details = page.getByRole('dialog')
  await expect(details).toContainText(f.bookings[0].booking_reference)
  await expect(details.getByRole('button', { name: 'Verify payment', exact: true })).toBeVisible()
  expect(await details.evaluate(el => el.scrollWidth <= el.clientWidth)).toBe(true)
  await page.getByRole('button', { name: 'Close details' }).click()
  await expect(page).toHaveURL(/\/admin\/review$/)
})
for (const destination of ['review', 'bookings']) test(`${destination} deep link denies a non-admin without fetching records`, async ({ page }) => {
  const dataRequests = []
  page.on('request', r => { if (/rest\/v1\/(bookings|rpc\/admin_payment_review_queue)/.test(r.url())) dataRequests.push(r.url()) })
  await login(page, destination === 'review' ? '/admin/review' : `/admin/bookings/${f.bookings[0].id}`)
  await expect(page.getByRole('alert')).toContainText('does not have Admin access')
  expect(dataRequests).toEqual([])
})
test('signed-out exact booking deep link survives login and reload', async ({ page }) => {
  await f.authorize(); const path = `/admin/bookings/${f.bookings[0].id}`
  await login(page, path)
  await expect(page.getByRole('dialog')).toContainText(f.bookings[0].booking_reference)
  await expect(page).toHaveURL(new RegExp(path + '$'))
  await page.reload()
  await expect(page.getByRole('dialog')).toContainText(f.bookings[0].booking_reference)
  await page.getByRole('button', { name: 'Close details' }).click()
  await expect(page).toHaveURL(/\/admin$/)
  await expect(page.getByLabel('Calendar date', { exact: true })).toBeVisible()
})
test('bank verification persists and leaves the queue; cash approval and receipt remain separate', async ({ page }) => {
  await f.authorize(); await login(page)
  await confirm(page, item(page, 0).getByRole('button', { name: 'Verify payment', exact: true }))
  await expect(item(page, 0)).toHaveCount(0)
  expect((await f.admin.from('booking_payments').select('status,paid_at').eq('booking_id', f.bookings[0].id).single()).data.status).toBe('paid')
  await item(page, 1).getByRole('link', { name: 'View booking' }).click()
  await expect(page.locator('dialog.admin-details')).toBeVisible()
  await confirm(page, page.locator('dialog.admin-details').getByRole('button', { name: 'Approve', exact: true }))
  await expect(page.getByRole('button', { name: 'Mark payment received', exact: true })).toBeVisible()
  const approved = (await f.admin.from('booking_payments').select('status,paid_at').eq('booking_id', f.bookings[1].id).single()).data
  expect(approved).toMatchObject({ status: 'approved', paid_at: null })
  await confirm(page, page.getByRole('button', { name: 'Mark payment received', exact: true }))
  await expect(page.getByRole('button', { name: 'Mark payment received', exact: true })).toHaveCount(0)
  await expect(page.getByRole('dialog').getByText('Confirmed · Paid', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Close details' }).click()
  await expect(page.locator('.admin-review-item')).toHaveCount(0)
})
test('removing a cash request requires deliberate confirmation and persists cancellation', async ({ page }) => {
  await f.authorize(); await login(page)
  await confirm(page, item(page, 1).getByRole('button', { name: 'Remove booking', exact: true }))
  await expect(item(page, 1)).toHaveCount(0)
  const result = (await f.admin.from('bookings').select('booking_status,cancelled_at').eq('id', f.bookings[1].id).single()).data
  expect(result.booking_status).toBe('cancelled'); expect(result.cancelled_at).toBeTruthy()
})
test('a transfer the client never declared stays listed and the Admin can remove it', async ({ page }) => {
  await f.prepare(0, 'bank_transfer', 'awaiting_transfer', 'awaiting_transfer')
  await f.authorize(); await login(page)
  await expect(item(page, 0)).toContainText('Transfer not yet declared by the client')
  await expect(item(page, 0).getByRole('button', { name: 'Verify payment', exact: true })).toBeVisible()
  await confirm(page, item(page, 0).getByRole('button', { name: 'Remove booking', exact: true }))
  await expect(page.locator('.admin-review-item')).toHaveCount(1)
  const result = (await f.admin.from('bookings').select('booking_status,cancelled_by_actor_type').eq('id', f.bookings[0].id).single()).data
  expect(result).toMatchObject({ booking_status: 'cancelled', cancelled_by_actor_type: 'admin' })
})
test('failed mutation keeps authoritative state, hides internal errors, and prevents duplicate submission', async ({ page }) => {
  await f.authorize(); await login(page, `/admin/bookings/${f.bookings[0].id}`)
  let requests = 0, release
  const gate = new Promise(resolve => { release = resolve })
  await page.route('**/rpc/admin_verify_bank_transfer', async route => { requests++; await gate; await route.fulfill({ status: 500, json: { message: 'secret SQL detail', code: 'XX000' } }) })
  await page.getByRole('button', { name: 'Verify payment', exact: true }).click()
  await page.getByRole('button', { name: 'Confirm verify payment', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Saving…' })).toBeDisabled()
  expect(requests).toBeLessThanOrEqual(1)
  release()
  await expect(page.getByRole('alert')).toContainText('Could not complete the payment action')
  await expect(page.getByText('secret SQL detail')).toHaveCount(0)
  await expect(page.getByRole('button', { name: 'Verify payment', exact: true })).toBeVisible()
  expect((await f.admin.from('booking_payments').select('status').eq('booking_id', f.bookings[0].id).single()).data.status).toBe('awaiting_verification')
})
test('stale action refreshes to the persisted state without claiming success', async ({ page }) => {
  await f.authorize(); await login(page, `/admin/bookings/${f.bookings[0].id}`)
  await page.getByRole('button', { name: 'Verify payment', exact: true }).click()
  await f.admin.from('bookings').update({ booking_status: 'confirmed' }).eq('id', f.bookings[0].id)
  await f.admin.from('booking_payments').update({ status: 'paid', paid_at: new Date().toISOString() }).eq('booking_id', f.bookings[0].id)
  await page.getByRole('button', { name: 'Confirm verify payment', exact: true }).click()
  await expect(page.getByRole('alert')).toContainText('This booking changed')
  await expect(page.getByRole('button', { name: 'Verify payment', exact: true })).toHaveCount(0)
  await expect(page.getByRole('dialog').getByText('Confirmed · Paid', { exact: true })).toBeVisible()
})
test('desktop Review uses compact navigation and the existing details panel', async ({ page }) => {
  await f.authorize(); await page.setViewportSize({ width: 1280, height: 900 }); await login(page)
  await expect(page.locator('.admin-review-item')).toHaveCount(2)
  expect((await page.getByRole('navigation', { name: 'Admin navigation' }).boundingBox()).height).toBeLessThan(70)
  await page.screenshot({ path: 'test-results/admin-review-desktop.png', fullPage: true })
  await item(page, 0).getByRole('link', { name: 'View booking' }).click()
  const box = await page.getByRole('dialog').boundingBox()
  expect(box.width).toBe(580)
  await page.screenshot({ path: 'test-results/admin-review-details-desktop.png' })
})
test('Escape cancels only the payment confirmation and restores its action focus', async ({ page }) => {
  await f.authorize(); await login(page, `/admin/bookings/${f.bookings[0].id}`)
  const details = page.locator('dialog.admin-details')
  const verify = details.getByRole('button', { name: 'Verify payment', exact: true })
  await verify.click()
  await expect(page.locator('dialog.admin-confirm')).toBeVisible()
  await page.keyboard.press('Escape')
  await expect(page.locator('dialog.admin-confirm')).toHaveCount(0)
  await expect(details).toBeVisible()
  await expect(verify).toBeFocused()
  expect((await f.admin.from('booking_payments').select('status').eq('booking_id', f.bookings[0].id).single()).data.status).toBe('awaiting_verification')
})
test('Review load failure is retryable and More offers safe navigation and sign-out', async ({ page }) => {
  await f.authorize()
  await page.route('**/rpc/admin_payment_review_queue?**', route => route.fulfill({ status: 403, json: { code: '42501', message: 'internal detail' } }))
  await login(page)
  await expect(page.getByRole('alert')).toContainText('Could not load payment reviews')
  await expect(page.getByText('internal detail')).toHaveCount(0)
  await page.unroute('**/rpc/admin_payment_review_queue?**')
  await page.getByRole('button', { name: 'Retry reviews' }).click()
  await expect(page.locator('.admin-review-item')).toHaveCount(2)
  const nav = page.getByRole('navigation', { name: 'Admin navigation' })
  await expect(nav.getByRole('button', { name: /Clients/ })).toBeDisabled()
  await nav.getByRole('link', { name: 'Calendar', exact: true }).click()
  await expect(page.getByLabel('Calendar date', { exact: true })).toBeVisible()
  await nav.getByRole('link', { name: 'More', exact: true }).click()
  await expect(page.getByRole('link', { name: 'Working hours and special days' })).toBeVisible()
  await page.getByRole('button', { name: 'Sign out', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Admin sign in' })).toBeVisible()
})


test('lost response after a committed transfer is safely retried with the same command key', async ({ page }) => {
  await f.authorize(); await login(page, `/admin/bookings/${f.bookings[0].id}`)
  const keys = []
  page.on('request', r => { if (r.url().endsWith('/rpc/admin_verify_bank_transfer')) keys.push(r.postDataJSON().p_request_id) })
  await page.route('**/rpc/admin_verify_bank_transfer', async route => {
    const response = await route.fetch()
    expect(response.ok()).toBe(true)
    // The real transaction committed, but the browser receives an unusable response.
    await route.fulfill({ status: 400, json: { message: 'Response lost' } })
  })
  await confirm(page, page.getByRole('button', { name: 'Verify payment', exact: true }))
  await expect(page.getByRole('alert')).toContainText('Could not complete')
  expect((await f.admin.from('booking_payments').select('status').eq('booking_id', f.bookings[0].id).single()).data.status).toBe('paid')
  await page.unroute('**/rpc/admin_verify_bank_transfer')
  await confirm(page, page.getByRole('button', { name: 'Verify payment', exact: true }))
  await expect(page.getByRole('dialog').getByText('Confirmed · Paid', { exact: true })).toBeVisible()
  expect(keys).toHaveLength(2); expect(keys[0]).toBe(keys[1])
  expect((await f.admin.from('command_requests').select('id').eq('scope', `admin-payment:${f.user.id}`)).data).toHaveLength(1)
  expect((await f.admin.from('event_outbox').select('id').eq('aggregate_id', f.bookings[0].id)).data).toHaveLength(1)
})

test('Calendar, Review and booking support browser Back and Forward', async ({ page }) => {
  await f.authorize(); await login(page, '/admin')
  await page.getByRole('link', { name: 'Review', exact: true }).click()
  await item(page, 0).getByRole('link', { name: 'View booking' }).click()
  await expect(page.getByRole('dialog')).toContainText(f.bookings[0].booking_reference)
  await page.goBack(); await expect(page).toHaveURL(/\/admin\/review$/)
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await page.goForward(); await expect(page.getByRole('dialog')).toContainText(f.bookings[0].booking_reference)
  await page.goBack(); await page.goBack()
  await expect(page).toHaveURL(/\/admin$/)
  await expect(page.getByLabel('Calendar date', { exact: true })).toBeVisible()
})

test('revoked Admin access during confirmation cannot mutate the payment', async ({ page }) => {
  await f.authorize(); await login(page)
  await item(page, 0).getByRole('button', { name: 'Verify payment', exact: true }).click()
  expect((await f.admin.from('admin_users').delete().eq('user_id', f.user.id)).error).toBeNull()
  await page.getByRole('button', { name: 'Confirm verify payment', exact: true }).click()
  await expect(page.getByRole('alert')).toContainText('Could not complete')
  expect((await f.admin.from('booking_payments').select('status').eq('booking_id', f.bookings[0].id).single()).data.status).toBe('awaiting_verification')
})


test('an older manual refresh cannot overwrite status fetched after a payment action', async ({ page }) => {
  await f.authorize(); await login(page, `/admin/bookings/${f.bookings[0].id}`)
  await expect(page.getByRole('button', { name: 'Verify payment', exact: true })).toBeVisible()
  let release, captured
  const gate = new Promise(resolve => { release = resolve })
  const ready = new Promise(resolve => { captured = resolve })
  let reads = 0
  await page.route('**/rest/v1/bookings?**', async route => {
    if (++reads !== 1) return route.continue()
    const response = await route.fetch(); captured(); await gate
    await route.fulfill({ response })
  })
  await page.getByRole('button', { name: 'Refresh booking', exact: true }).click()
  await ready
  await confirm(page, page.getByRole('button', { name: 'Verify payment', exact: true }))
  await expect(page.getByRole('dialog').getByText('Confirmed · Paid', { exact: true })).toBeVisible()
  const oldRead = page.waitForResponse(r => r.url().includes('/rest/v1/bookings?'))
  release(); await (await oldRead).finished()
  await page.evaluate(() => new Promise(resolve => requestAnimationFrame(() => requestAnimationFrame(resolve))))
  await expect(page.getByRole('dialog').getByText('Confirmed · Paid', { exact: true })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Verify payment', exact: true })).toHaveCount(0)
})
