import { test, expect } from '@playwright/test'
import { paymentReviewFixture } from '../paymentReviewFixture.js'

let f, originalWeek
test.beforeEach(async () => {
  f = await paymentReviewFixture()
  originalWeek = (await f.admin.from('working_hours').select('*').order('weekday')).data
})
test.afterEach(async () => {
  await f.admin.from('working_hours').upsert(originalWeek, { onConflict: 'weekday' })
  await f.admin.from('working_hours_overrides').delete().eq('date', f.bookings[0].date).is('note', null)
  await f.admin.from('working_hours_overrides').delete().eq('note', 'Family day')
  await f.admin.from('calendar_blocks').delete().eq('title', 'Dentist')
  await f.admin.from('calendar_blocks').delete().eq('title', 'Summer break')
  await f?.cleanup()
})

async function signIn(page, path) {
  await page.goto(path)
  await page.getByLabel('Email', { exact: true }).fill(f.email)
  await page.getByLabel('Password', { exact: true }).fill(f.password)
  await page.getByRole('button', { name: 'Sign in', exact: true }).click()
}

test('the usual week can be changed, checked before saving, and is saved', async ({ page }) => {
  await f.authorize()
  await signIn(page, '/admin/schedule')
  await expect(page.getByRole('heading', { name: 'Working hours' })).toBeVisible()
  const saturday = page.getByRole('group', { name: 'Saturday' })
  await expect(saturday.getByRole('checkbox', { name: 'Working day' })).not.toBeChecked()
  await saturday.getByRole('checkbox', { name: 'Working day' }).check()
  await saturday.getByLabel('Saturday start').selectOption('600')
  await saturday.getByLabel('Saturday end').selectOption('600')
  await expect(saturday.getByRole('alert')).toHaveText('The end time must be after the start time.')
  await expect(page.getByRole('button', { name: 'Save my hours' })).toBeDisabled()
  await saturday.getByLabel('Saturday end').selectOption('840')
  await saturday.getByLabel('Saturday first appointment').selectOption('fixed')
  await saturday.getByLabel('Saturday first appointment time').selectOption('660')
  await page.getByRole('button', { name: 'Save my hours' }).click()
  await expect(page.getByText('Saved. New bookings will follow these hours.')).toBeVisible()
  const row = (await f.admin.from('working_hours').select('*').eq('weekday', 6).single()).data
  expect(row).toMatchObject({ available: true, start_minutes: 600, end_minutes: 840, start_mode: 'fixed', fixed_start_minutes: 660 })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
})

test('a day off over a live booking warns first, never moves the booking, and can be removed', async ({ page }) => {
  await f.authorize()
  await signIn(page, '/admin/schedule')
  await page.getByRole('tab', { name: 'Special days' }).click()
  await page.getByRole('button', { name: 'Add a special day' }).click()
  await page.getByLabel('Date').fill(f.bookings[0].date)
  await page.getByLabel('Note (only you see this)').fill('Family day')
  await page.getByRole('button', { name: 'Save', exact: true }).click()
  await expect(page.getByRole('alert').filter({ hasText: 'This clashes with' })).toBeVisible()
  expect((await f.admin.from('working_hours_overrides').select('date').eq('date', f.bookings[0].date).eq('note', 'Family day')).data).toHaveLength(0)
  await page.getByRole('button', { name: 'Save anyway' }).click()
  await expect(page.getByText('Saved.')).toBeVisible()
  await expect(page.getByRole('list').filter({ hasText: 'Family day' })).toContainText('Day off')
  expect((await f.admin.from('bookings').select('booking_status').eq('id', f.bookings[0].id).single()).data.booking_status).toBe('awaiting_payment_verification')
  await page.getByRole('button', { name: 'Remove', exact: true }).click()
  await expect(page.getByText('Removed. That day follows your usual week again.')).toBeVisible()
})

test('time can be blocked from the calendar, with a warning about clashes, then changed and removed', async ({ page }) => {
  await f.authorize()
  await signIn(page, `/admin?date=${f.bookings[0].date}`)
  await page.getByRole('button', { name: 'Block time', exact: true }).click()
  const dialog = page.locator('dialog.admin-action')
  await expect(dialog).toBeVisible()
  await dialog.getByLabel('A personal event').check()
  await dialog.getByLabel('Name of the event').fill('Dentist')
  await dialog.getByRole('button', { name: 'Block this time' }).click()
  await expect(dialog.getByRole('alert').filter({ hasText: 'clashes with' })).toBeVisible()
  expect((await f.admin.from('calendar_blocks').select('id').eq('title', 'Dentist')).data).toHaveLength(0)
  await dialog.getByRole('button', { name: 'Save anyway' }).click()
  const block = page.getByRole('button', { name: /Dentist/ })
  await expect(block).toBeVisible()
  expect((await f.admin.from('calendar_blocks').select('kind,title,start_minutes,end_minutes').eq('title', 'Dentist').single()).data).toMatchObject({ kind: 'personal_event', start_minutes: 720, end_minutes: 780 })
  await block.click()
  await expect(dialog.getByRole('heading', { name: 'Change blocked time' })).toBeVisible()
  await dialog.getByRole('button', { name: 'Remove', exact: true }).click()
  await dialog.getByRole('button', { name: 'Yes, remove' }).click()
  await expect(page.getByRole('button', { name: /Dentist/ })).toHaveCount(0)
  expect((await f.admin.from('calendar_blocks').select('id').eq('title', 'Dentist')).data).toHaveLength(0)
})

test('a personal event needs a name, and the dialog fits a small phone', async ({ page }) => {
  await page.setViewportSize({ width: 320, height: 640 })
  await f.authorize()
  await signIn(page, `/admin?date=${f.date}`)
  await page.getByRole('button', { name: 'Block time', exact: true }).click()
  const dialog = page.locator('dialog.admin-action')
  await dialog.getByLabel('A personal event').check()
  await expect(dialog.getByRole('alert')).toHaveText('Give the personal event a name.')
  await expect(dialog.getByRole('button', { name: 'Block this time' })).toBeDisabled()
  expect(await dialog.evaluate(el => el.scrollWidth <= el.clientWidth)).toBe(true)
  await page.screenshot({ path: 'test-results/admin-block-dialog-320.png' })
})

test('a holiday over several days, starting and ending part-way through a day, is one block that can be changed and removed', async ({ page }) => {
  await f.authorize()
  const day = offset => new Date(Date.now() + offset * 86400000).toISOString().slice(0, 10)
  const first = day(120), last = day(122)
  await signIn(page, '/admin/schedule')
  await page.getByRole('tab', { name: 'Special days' }).click()
  await page.getByRole('button', { name: 'Block time', exact: true }).click()
  const dialog = page.locator('dialog.admin-action')
  await dialog.getByLabel('Label (optional)').fill('Summer break')
  await dialog.getByLabel('Start date').fill(first)
  await expect(dialog.getByLabel('End date')).toHaveValue(first)
  await dialog.getByLabel('End date').fill(last)
  await dialog.getByLabel('Start time').selectOption('840')
  await dialog.getByLabel('End time').selectOption('600')
  await expect(dialog.getByRole('status')).toContainText('3 days')
  expect(await dialog.evaluate(el => el.scrollWidth <= el.clientWidth)).toBe(true)
  await dialog.getByRole('button', { name: 'Block this time' }).click()
  const item = page.locator('.admin-blocked-time li', { hasText: 'Summer break' })
  await expect(item).toContainText(' to ')
  const rows = (await f.admin.from('calendar_blocks').select('date,start_minutes,end_minutes').eq('title', 'Summer break').order('date')).data
  expect(rows).toEqual([{ date: first, start_minutes: 840, end_minutes: 1440 }, { date: day(121), start_minutes: 0, end_minutes: 1440 }, { date: last, start_minutes: 0, end_minutes: 600 }])

  await item.getByRole('button', { name: 'Change' }).click()
  await expect(dialog.getByRole('heading', { name: 'Change blocked time' })).toBeVisible()
  await expect(dialog.getByLabel('End date')).toHaveValue(last)
  await dialog.getByLabel('End date').fill(day(121))
  await dialog.getByRole('button', { name: 'Save changes' }).click()
  await expect(dialog).toHaveCount(0)
  expect((await f.admin.from('calendar_blocks').select('id').eq('title', 'Summer break')).data).toHaveLength(2)

  await item.getByRole('button', { name: 'Change' }).click()
  await dialog.getByRole('button', { name: 'Remove', exact: true }).click()
  await expect(dialog).toContainText('all 2 days')
  await dialog.getByRole('button', { name: 'Yes, remove' }).click()
  await expect(page.locator('.admin-blocked-time li', { hasText: 'Summer break' })).toHaveCount(0)
  expect((await f.admin.from('calendar_blocks').select('id').eq('title', 'Summer break')).data).toHaveLength(0)
})
